language: node_js
node_js:
- node
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: andreas@softbrix.se
  api_key:
    secure: MQ3aIR8PpSPUbQMZrtzg7sSSWfYVzSSjC9K8JfsrSjSOy9xE9GbuXoXO9wp8NmijHSldgDwhVi4BA7uJ0vKsFOpHeFHmmsPCqXN9k6zWt5hZM07qWQbf5nivF2gMEOO6NN5Ccx76eylcW3KLCY0dDPSl+cBmdcUVfkUvUfCo+uULFMeA4mDdsehJWgqQT5/BVzsTqgq8SzbIhE+Edz60WrwSgPVQTuignH/dsbw6uupnnOMGrNhtcB7g287QsNQPaAXdXVtLp45oCr9Bw26QPiS15m0r4hnWmRY2W0dHWqJV8U4FOrjH1id5rdafSHGNzBqapvQGHQOOcmn7jmgRXpBGuk8zndTP9+P7Hu9UH+E1eR31ngp1QIL7RAFnGoJUl5Ayk2D3WUfx5I9PwEmXXAyRLPG6Gy15EPaUcxcVG8mGRp3bHDriz3VMZTaUrKVNNmNYVmRLYBQVuc7WUuhtDJ9oZybNwKbdWxyJfXHebsf8jbKeAEa5HXPE2YcexQvNBG9e5tCE182Jo7ogqfcSw79qTJY2r22NP1RQ6K1esww/k76/kETZnMbq2Dpy8H0W5YcZezbkHw/N9tgt+kBbcvn/iD2Ypcp/g/V6i4AdfjzdzO3RRlKlP7gc0n3nrA4zc2B2ep1s5s+3amQRgavzJwv/X8Wp9L9a+qzV/p7jKB8=
  on:
    tags: true
    repo: softbrix/sjotorp_image
