language: node_js
node_js:
- node
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: andreas@softbrix.se
  api_key:
    secure: M/EGwOY7UmA2XuJ7ZrD8vwIwqBcT/USG8rMGRXODv8b6hsv/kfkYuTuKqlnLnn/Npx4amx8fvUjyrIZ9q5+rK8ciLrHTQTixy0p9VowcssxD99jrkoUwx7zyMiC4tPVsciU6MujVBNJogNqrasfNJRQCrokqc0Aa4wAGG4DHhN/nOfG77cGl/F1WXePoXivGyjqWksjnmCCi9+471vZ7GRrhOGLNwAJDF1SHOa7NVlnYL9za22tDUxvB/Es5w7R1h4Pkid/hauBA1mnX6zW/IVJ81GPGXD6BfJdn+7oOOtBGrfOTzDED18ZIjRjpr4pBRzUQ/NC/hOwxUb5ioqdw5jMlojlOgc3yYKSd9j++icyZwOA7Sug3atT1ix7cvk7MTbcz3P36HBWiYcjIs0LT8j+jtzF5hmtXTDh7MJlZWRZN1qrKEew5jrs6qrjkGZoWw2smDStCcPe22obWEe54IATb6NTiWXZ/Rudpz/FOKssyAYBvvw4AIa4TmUrvu0G9UDAJh5tAZhy+x2inoisjL0jGpH9xm29CfRHGA1gH4MLAk/1nJ9r2A9xngqDDUEw6iPeNuydBNndLyX0mVIpK81/namFBa3rmRKCLu/OfbrmggOUoU3Tf9cphJHaBObSxzNnIc7ioxgdZVvvsRHZGxxd4lTm2J5L1jmAXc7iQAL4=
  on:
    tags: true
    repo: softbrix/sjotorp_image
